- LICENSE
- src/components/app.jsx
- src/components/app.test.js
- src/components/footer/footer.jsx
- src/components/label/label.jsx
- src/components/popup/details/details.jsx
- src/components/popup/details/details.less
- src/components/popup/details/purposes/purposes.jsx
- src/components/popup/details/purposes/purposes.less
- src/components/popup/details/purposes/purposes.test.js
- src/components/popup/details/vendors/vendors.jsx
- src/components/popup/details/vendors/vendors.less
- src/components/popup/intro/intro.jsx
- src/components/popup/popup.jsx
- src/components/popup/popup.less
- src/docs/assets/vendors.json
- src/docs/components/intro/intro.jsx
- src/lib/cmp.js
- src/lib/init.js
- src/lib/localize.js
- src/lib/localize.test.js
- src/lib/store.js
- src/lib/translations.js
Closes:
- https://github.com/digi-trust/cmp/issues/49 - Remove UX functionality that is non-compliant
- https://github.com/digi-trust/cmp/issues/51 - Changes to the UI (most of them, some work is left to be done)
- https://github.com/digi-trust/cmp/issues/31 - Configurable domain name on intro
- https://github.com/digi-trust/cmp/issues/50 - Update language
- https://github.com/digi-trust/cmp/issues/38 - Remove remaining references to AppNexus
> UI changes, implement configurable localization

- src/lib/cmp.js
Only to fix current demo page.
Issue for full solution -  #54
> fixed demo page to render at least somthing

- src/components/popup/details/purposes/purposes.jsx
- src/components/popup/details/purposes/purposes.less
- src/components/popup/details/vendors/vendors.jsx
- src/components/popup/intro/intro.less
- src/docs/assets/portal.js
- src/lib/init.js
- src/lib/vendor.js
Closes 
- https://github.com/digi-trust/cmp/issues/59
Fixes
- https://github.com/digi-trust/cmp/issues/58
> use configured vendor list location, Firefox bugfix

- src/docs/lib/stub.js
- src/lib/cmp.js
- src/lib/cmp.test.js
- src/lib/store.js
Changed callback execution behaviour according to framework requirements.
> Execute cmp framework defined callbacks after consent received

- src/docs/assets/portal.js
- src/lib/cookie/cookie.js
closes - #43
Works on Mac OS Safari & iOS Safari (only newest versions tested), is it enough?
> fallback to first party cookies

- src/lib/translations.js
I feel like the German especially has a lot of random capitalization in it. Maybe someone else who speaks it can take a look as well?
@braizhas FYI, there are some purposeful spaces at the start and/or end of some strings.
> add Spanish and German translations

- webpack.config.babel.js
Serve all the required content using single js file.
> Font loading fixed

- src/components/app.less
- src/lib/cmp.js
Toolbox should be on top of all the site content.
> default z-index for popups, metadata fix

- metadata.json
- src/components/popup/details/purposes/purposes.jsx
- src/components/popup/intro/footer.jsx
- src/components/popup/intro/footerV2.jsx
- src/components/popup/intro/intro.jsx
- src/components/popup/intro/introV2.jsx
- src/components/popup/popup.jsx
- src/components/popup/popupFooter.jsx
- src/lib/cmp.js
- src/lib/cmp.test.js
- src/lib/init.js
- src/lib/store.js
- src/lib/translations.js
- src/lib/utils.js
- src/lib/utils.test.js
- src/lib/vendor.js
- src/lib/vendor.test.js
Support for features commented out in code (store.js) until IAB translates those as well.
Fixes https://github.com/digi-trust/cmp/pull/94 most of the way; features need to be retrieved as well but we are currently blocked by the IAB's translations.
Also adds a new command for pubs to tap into, `gdprInScope`
> fetch purposes in local language

- src/lib/cmp.js
- src/lib/store.js
- src/lib/utils.js
- src/lib/utils.test.js
Found while investigating https://github.com/digi-trust/cmp/issues/108
> bugfix for getConsentsCount

- .eslintrc
- src/components/app.jsx
- src/components/app.test.js
- src/components/closebutton/closebutton.jsx
- src/components/footer/footer.jsx
- src/components/footer/footer.less
- src/components/popup/details/details.jsx
- src/components/popup/details/details.test.js
- src/components/popup/details/purposes/purposes.jsx
- src/components/popup/details/purposes/purposes.test.js
- src/components/popup/details/vendors/vendors.jsx
- src/components/popup/details/vendors/vendors.test.js
- src/components/popup/intro/footer.jsx
- src/components/popup/intro/footer.less
- src/components/popup/intro/footerV2.jsx
- src/components/popup/intro/footerV2.less
- src/components/popup/intro/intro.jsx
- src/components/popup/intro/introV2.jsx
- src/components/popup/popup.jsx
- src/components/popup/popup.test.js
- src/components/popup/popupFooter.jsx
- src/lib/config.js
- src/lib/config.test.js
Closes https://github.com/digi-trust/cmp/issues/26, https://github.com/digi-trust/cmp/issues/96
~Going to try and continue work on supporting externally loaded fonts and will add to this PR if it hasn't been merged by the time I get it to work.~
Update: got dynamic fonts to work :)
> support for customizable CSS, loads dynamically

- src/components/app.jsx
- src/components/popup/details/purposes/purposes.less
- src/components/popup/intro/footer.less
- src/components/popup/intro/footerV2.less
- src/components/popup/popup.jsx
- src/components/popup/popup.less
- src/components/popup/popupFooter.jsx
- src/components/popup/popupFooter.less
- src/lib/config.js
- src/lib/init.js
Addresses https://github.com/digi-trust/cmp/issues/118
> Block browsing option

- src/components/footer/footer.jsx
- src/components/popup/intro/footer.jsx
- src/components/popup/intro/footerV2.jsx
- src/components/popup/intro/intro.jsx
- src/components/popup/intro/introV2.jsx
- src/lib/translations.js
Addresses https://github.com/digi-trust/cmp/issues/97 but we need translations for the phrase "Accept all" in all the major languages.
> change wording of 'accept all' button

- src/lib/cmp.js
- src/lib/cmp.test.js
- src/lib/config.js
- src/lib/config.test.js
Closes https://github.com/digi-trust/cmp/issues/120
> add showConfig CMP function

- src/components/app.jsx
- src/components/popup/intro/footer.jsx
- src/components/popup/intro/footerV2.jsx
- src/components/popup/intro/footerV2.less
- src/components/popup/intro/introThin.jsx
- src/components/popup/intro/introThin.less
- src/components/popup/intro/introV2.jsx
- src/components/popup/popupThin.jsx
- src/components/popup/popupThin.less
- src/lib/cmp.js
- src/lib/store.js
Addresses https://github.com/digi-trust/cmp/issues/119
**Example:**
> Thin footer

- src/components/app.jsx
Fixes https://github.com/digi-trust/cmp/issues/130
> Make sure current locale is using two letter abbreviation

- src/components/popup/intro/footer.jsx
- src/components/popup/intro/footerV2.jsx
Closes https://github.com/digi-trust/cmp/issues/128
> 128 add custom purposes to intro screen

- src/lambdaFunction.js
Addresses https://github.com/digi-trust/cmp/issues/33
There is a versioning system on AWS, but it would good for documentation's sake to keep it here as well.
> checking Lambda function into version control

- src/lib/translations.js
@anissaconnor and @hbruce27 
The standardized language document is out of date and doesn't have all the keys necessary. I would recommend that we draft a new version that is more visual in nature. Sync up with me for a demo if needed.
> added Czech translation, some major pieces missing

- .eslintrc
- src/components/popup/details/purposes/purposes.jsx
- src/docs/assets/portal.js
- src/docs/assets/purposes.json
- src/lib/cmp.test.js
- src/lib/config.js
- src/lib/cookie/cookie.js
- src/lib/cookie/cookie.test.js
- src/lib/init.js
- src/lib/store.js
- src/lib/store.test.js
We should do some extensive QA on this one.
Closes https://github.com/digi-trust/cmp/issues/139
> 139 support group consent

- package-lock.json
- package.json
- protractor.conf.js
- spec/intro.spec.js
- spec/intro/intro.spec.js
- spec/purposes.spec.js
- spec/support/jasmine.json
- spec/support/utils.js
- spec/vendors.spec.js
- src/components/button/button.jsx
- src/components/popup/details/vendors/vendors.jsx
- src/components/popup/intro/footerV2.jsx
- src/index.html
Addresses https://github.com/digi-trust/cmp/issues/129
> 129 e2e testing

- src/components/app.jsx
Addresses https://github.com/digi-trust/cmp/issues/12
> Compatibility fixes for Microsoft browsers

- package-lock.json
- package.json
- protractor.conf.js
- spec/configuration.spec.js
- spec/support/utils.js
- src/components/popup/intro/footer.jsx
- src/components/popup/intro/footerV2.jsx
- src/e2e/layout-modal.html
- src/e2e/layout-thin.html
- webpack.config.babel.js
Adds Firefox to local testing harness, layout configuration specs
> 146 e2e tests

- spec/configuration.spec.js
- src/components/popup/intro/intro.jsx
- src/components/popup/intro/introV2.jsx
- src/e2e/company_name.html
- src/lib/config.js
- webpack.config.babel.js
Closes https://github.com/digi-trust/cmp/issues/162
> add companyName to configuration options

- src/lib/init.js
Closes https://github.com/digi-trust/cmp/issues/163
> 163 append locator frame logic to init

- src/lib/utils.js
Fixes https://github.com/digi-trust/cmp/issues/171
> Fix empty set on IE11

- src/lib/cmp.js
- src/lib/cmp.test.js
- src/lib/portal.js
- src/lib/store.js
- src/lib/utils.js
Closes https://github.com/digi-trust/cmp/issues/180 and https://github.com/digi-trust/cmp/issues/182
> 180 ie cookie fix

- src/components/app.less
- src/components/button/button.less
- src/components/popup/details/purposes/purposes.less
- src/components/popup/intro/footer.less
- src/components/popup/intro/intro.less
- yarn.lock
> Broken formatting

- src/components/app.jsx
- src/lib/cmp.js
- src/lib/store.js
- src/lib/utils.js
> Added hasOwnProperty checks to all for/in loops in the cmp src

- src/lib/vendor.js
update vendor list against global vendor list
> update Vendor list
